language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
install: 
  - pip install -r requirements.txt
  - python setup.py install
  - pip install coveralls
  - pip install flake8
script:
  - flake8 calexicon/ --max-complexity 4 --max-line-length 99
  - coverage run --source=calexicon setup.py test
after_success:
  coveralls

branches:
  only:
    - master

