language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
install: 
  - pip install -r requirements.txt
  - python setup.py install
  - pip install coveralls
script:
  coverage run --source=calexicon setup.py test
after_success:
  coveralls

branches:
  only:
    - master

